// Mock for canvas module when native bindings are not available
module.exports = {
  createCanvas: () => ({
    getContext: () => ({
      fillRect: () => {},
      clearRect: () => {},
      getImageData: () => ({ data: [] }),
      putImageData: () => {},
      createImageData: () => [],
      setTransform: () => {},
      drawImage: () => {},
      save: () => {},
      restore: () => {},
      fillText: () => {},
      measureText: () => ({ width: 0 }),
      transform: () => {},
      translate: () => {},
      scale: () => {},
      rotate: () => {},
      beginPath: () => {},
      closePath: () => {},
      moveTo: () => {},
      lineTo: () => {},
      arc: () => {},
      fill: () => {},
      stroke: () => {},
      clip: () => {},
    }),
    toBuffer: () => Buffer.from([]),
    toDataURL: () => "",
  }),
  loadImage: () => Promise.resolve({}),
  Image: class Image {},
  registerFont: () => {},
};
