import type { ScreenBox } from "./boxes.js";
import type { Verification } from "./verification.js";

export type OutputImageFormat = "jpeg" | "png" | "avif" | undefined | null;

/**
 * A dictionary/map of citations keyed by citationKey (a 16-char hash).
 *
 * This is an OBJECT, not an array. To check if empty, use:
 * ```typescript
 * if (Object.keys(citations).length === 0) { ... }
 * ```
 *
 * Keys are generated by `generateCitationKey()` and are deterministic hashes
 * based on citation content (NOT simple numeric indices like "1", "2", "3").
 *
 * @example
 * ```typescript
 * const citations: CitationRecord = {
 *   "a1b2c3d4e5f67890": { pageNumber: 1, fullPhrase: "Revenue grew 23%" },
 *   "f9e8d7c6b5a43210": { pageNumber: 2, fullPhrase: "Costs decreased 15%" },
 * };
 *
 * // Iterate over citations
 * for (const [citationKey, citation] of Object.entries(citations)) {
 *   console.log(`Citation ${citationKey}:`, citation.fullPhrase);
 * }
 *
 * // Check count
 * const count = Object.keys(citations).length;
 * ```
 */
export type CitationRecord = Record<string, Citation>;

/**
 * A dictionary/map of verifications keyed by citationKey (a 16-char hash).
 *
 * This is an OBJECT, not an array. To check if empty, use:
 * ```typescript
 * if (Object.keys(verifications).length === 0) { ... }
 * ```
 *
 * Keys match the citationKey from CitationRecord for easy lookup.
 *
 * @example
 * ```typescript
 * const verifications: VerificationRecord = {
 *   "a1b2c3d4e5f67890": { status: "found", verifiedPageNumber: 1 },
 *   "f9e8d7c6b5a43210": { status: "not_found" },
 * };
 *
 * // Iterate over verifications
 * for (const [citationKey, verification] of Object.entries(verifications)) {
 *   console.log(`Citation ${citationKey} status:`, verification.status);
 * }
 * ```
 */
export type VerificationRecord = Record<string, Verification>;

export const DEFAULT_OUTPUT_IMAGE_FORMAT = "avif" as const;
export interface VerifyCitationResponse {
  verifications: VerificationRecord;
}

export interface VerifyCitationRequest {
  attachmentId: string;
  citations: CitationRecord;
  outputImageFormat?: OutputImageFormat;
  apiKey?: string; // Optional API key for authentication

  /**
   * When true, the backend will persist proof artifacts (images, metadata)
   * and return proofId, proofUrl, and proofImageUrl in the response.
   * @default false
   */
  generateProofUrls?: boolean;

  /**
   * Proof URL configuration. Only used when generateProofUrls is true.
   */
  proofConfig?: {
    /** Access control for proof URLs */
    access?: "signed" | "workspace" | "public";
    /** Expiry duration for signed URLs (only used when access is "signed") */
    signedUrlExpiry?: "1h" | "24h" | "7d" | "30d" | "90d" | "1y";
    /** Image format for proof images */
    imageFormat?: "png" | "jpeg" | "avif" | "webp";
    /** Whether to also return base64 images inline (in addition to URLs) */
    includeBase64?: boolean;
  };
}

/**
 * Citation type discriminator.
 * - `"document"`: PDF or uploaded document citation (uses attachmentId, pageNumber, lineIds)
 * - `"url"`: URL/web citation (uses url, domain, title, etc.)
 */
export type CitationType = "document" | "url";

/**
 * Source/platform type for categorization and display.
 * Used for icon selection and grouping in sources lists.
 */
export type SourceType =
  | "web" // Generic web page
  | "pdf" // PDF document
  | "document" // Uploaded document
  | "social" // Social media (X/Twitter, Facebook, etc.)
  | "video" // Video platforms (YouTube, Twitch, etc.)
  | "news" // News articles
  | "academic" // Academic papers/journals
  | "code" // Code repositories (GitHub, etc.)
  | "forum" // Forums/discussion boards (Reddit, etc.)
  | "commerce" // E-commerce sites
  | "reference" // Reference sites (Wikipedia, etc.)
  | "unknown"; // Unknown/other

/**
 * Unified citation interface for both document and URL-based citations.
 *
 * Use `type` to discriminate:
 * - `type: "document"` - Uses attachmentId, pageNumber, lineIds for document citations
 * - `type: "url"` - Uses url, domain, title, etc. for web citations
 *
 * Common fields (used by both types):
 * - `fullPhrase`: The full context/excerpt containing the cited information
 * - `anchorText`: The specific anchor text being cited (must be substring of fullPhrase)
 * - `citationNumber`: Citation number for display (e.g., [1], [2])
 *
 * @example Document citation
 * ```typescript
 * const docCitation: Citation = {
 *   type: "document",
 *   attachmentId: "abc123",
 *   pageNumber: 5,
 *   lineIds: [12, 13],
 *   fullPhrase: "Revenue increased by 15% in Q4.",
 *   anchorText: "increased by 15%",
 *   citationNumber: 1,
 * };
 * ```
 *
 * @example URL citation
 * ```typescript
 * const urlCitation: Citation = {
 *   type: "url",
 *   url: "https://example.com/article",
 *   domain: "example.com",
 *   title: "Q4 Financial Report",
 *   fullPhrase: "The TGU transitions require control, not brute strength.",
 *   anchorText: "require control, not brute strength",
 *   citationNumber: 1,
 * };
 * ```
 */
export interface Citation {
  /**
   * Citation type discriminator.
   * - `"document"`: PDF/uploaded document (default if not specified)
   * - `"url"`: Web URL citation
   */
  type?: CitationType;

  // ==========================================================================
  // Common fields (used by both document and URL citations)
  // ==========================================================================

  /** The full context/excerpt containing the cited information */
  fullPhrase?: string | null;

  /** The specific anchor text being cited (should be substring of fullPhrase) */
  anchorText?: string | null;

  /** Citation number for display (e.g., [1], [2], [3]) */
  citationNumber?: number;

  /** Reasoning for why this citation was included */
  reasoning?: string | null;

  /** Text that appears before the citation marker */
  beforeCite?: string;

  // ==========================================================================
  // Document citation fields (type: "document")
  // ==========================================================================

  /** Attachment ID for document citations */
  attachmentId?: string;

  /** Page number in the document */
  pageNumber?: number | null;

  /** Line IDs within the page */
  lineIds?: number[] | null;

  /** Start page ID for multi-page citations */
  startPageId?: string | null;

  /** Selection box coordinates in the document */
  selection?: ScreenBox | null;

  // ==========================================================================
  // URL citation fields (type: "url")
  // ==========================================================================

  /** The source URL */
  url?: string;

  /** Display domain (e.g., "example.com", "fitandwell.com") */
  domain?: string;

  /** Page/article title */
  title?: string;

  /** Brief description or snippet from the page */
  description?: string;

  /** Favicon URL for the source */
  faviconUrl?: string;

  /** Platform/source type for categorization (e.g., "video", "news", "social") */
  sourceType?: SourceType;

  /** Platform name (e.g., "Twitch", "YouTube", "Reddit") */
  platform?: string;

  /** Site name (e.g., "Fit&Well", "Garage Gym Reviews") */
  siteName?: string;

  /** Author name if available */
  author?: string;

  /** Publication date */
  publishedAt?: Date | string;

  /** Open Graph or social media image URL */
  imageUrl?: string;

  /** When the source was accessed/verified */
  accessedAt?: Date | string;

  // ==========================================================================
  // Audio/Video citation fields (can be used with both types)
  // ==========================================================================

  /** Timestamps for audio/video citations */
  timestamps?: {
    startTime?: string;
    endTime?: string;
  };
}

export interface CitationStatus {
  isVerified: boolean;
  isMiss: boolean;
  isPartialMatch: boolean;
  isPending: boolean;
}

/**
 * Metadata for a source in an aggregated sources list.
 * Used by SourcesListComponent to display collected citations.
 */
export interface SourceMeta {
  /** Unique identifier for this source */
  id: string;
  /** The source URL */
  url: string;
  /** Page/document title */
  title: string;
  /** Display domain without www prefix */
  domain: string;
  /** Platform/source type */
  sourceType?: SourceType;
  /** Favicon URL */
  faviconUrl?: string;
  /** Citation numbers that reference this source */
  citationNumbers?: number[];
  /** Number of times this source is cited */
  citationCount?: number;
  /** Relevant excerpts/quotes from this source */
  excerpts?: string[];
  /** Verification status if verified */
  verificationStatus?: "verified" | "partial" | "pending" | "failed" | "unknown";
  /** When the source was accessed */
  accessedAt?: Date | string;
}
