import type { Verification } from "./verification.js";

/**
 * Image format for proof images, verification screenshots, and output.
 */
export type ImageFormat = "jpeg" | "png" | "avif" | "webp";

/**
 * A dictionary/map of citations keyed by citationKey (a 16-char hash).
 *
 * This is an OBJECT, not an array. To check if empty, use:
 * ```typescript
 * if (Object.keys(citations).length === 0) { ... }
 * ```
 *
 * Keys are generated by `generateCitationKey()` and are deterministic hashes
 * based on citation content (NOT simple numeric indices like "1", "2", "3").
 *
 * @example
 * ```typescript
 * const citations: CitationRecord = {
 *   "a1b2c3d4e5f67890": { type: "document", pageNumber: 1, fullPhrase: "Revenue grew 23%" },
 *   "f9e8d7c6b5a43210": { type: "document", pageNumber: 2, fullPhrase: "Costs decreased 15%" },
 * };
 *
 * // Iterate over citations
 * for (const [citationKey, citation] of Object.entries(citations)) {
 *   console.log(`Citation ${citationKey}:`, citation.fullPhrase);
 * }
 *
 * // Check count
 * const count = Object.keys(citations).length;
 * ```
 */
export type CitationRecord = Record<string, Citation>;

/**
 * A dictionary/map of verifications keyed by citationKey (a 16-char hash).
 *
 * This is an OBJECT, not an array. To check if empty, use:
 * ```typescript
 * if (Object.keys(verifications).length === 0) { ... }
 * ```
 *
 * Keys match the citationKey from CitationRecord for easy lookup.
 *
 * @example
 * ```typescript
 * const verifications: VerificationRecord = {
 *   "a1b2c3d4e5f67890": { status: "found" },
 *   "f9e8d7c6b5a43210": { status: "not_found" },
 * };
 *
 * // Iterate over verifications
 * for (const [citationKey, verification] of Object.entries(verifications)) {
 *   console.log(`Citation ${citationKey} status:`, verification.status);
 * }
 * ```
 */
export type VerificationRecord = Record<string, Verification>;

export const DEFAULT_OUTPUT_IMAGE_FORMAT = "avif" as const;

export interface VerifyCitationResponse {
  verifications: VerificationRecord;
}

export interface VerifyCitationRequest {
  attachmentId: string;
  citations: CitationRecord;
  outputImageFormat?: ImageFormat;
  apiKey?: string;
  /** Developer's end-user identifier for usage attribution */
  endUserId?: string;
}

/**
 * Citation type discriminator.
 * - `"document"`: PDF or uploaded document citation (uses attachmentId, pageNumber, lineIds)
 * - `"url"`: URL/web citation (uses url, domain, title, etc.)
 */
export type CitationType = "document" | "url";

/**
 * Source/platform type for categorization and display.
 * Used for icon selection and grouping in sources lists.
 */
export type SourceType =
  | "web"
  | "pdf"
  | "document"
  | "social"
  | "video"
  | "news"
  | "academic"
  | "code"
  | "forum"
  | "commerce"
  | "reference"
  | "unknown";

/**
 * Common fields shared by all citation types.
 * Only contains fields that are semantically valid for both document and URL citations.
 */
interface CitationBase {
  /** The full context/excerpt containing the cited information */
  fullPhrase?: string;

  /** The specific anchor text being cited (should be substring of fullPhrase) */
  anchorText?: string;

  /** Citation number for display (e.g., [1], [2], [3]) */
  citationNumber?: number;

  /** Reasoning for why this citation was included */
  reasoning?: string;

  /** Timestamps for audio/video citations */
  timestamps?: {
    startTime?: string;
    endTime?: string;
  };
}

/**
 * Document citation — PDF or uploaded document.
 * Uses attachmentId, pageNumber, lineIds for verification.
 *
 * @example
 * ```typescript
 * const docCitation: DocumentCitation = {
 *   type: "document",
 *   attachmentId: "abc123",
 *   pageNumber: 5,
 *   lineIds: [12, 13],
 *   fullPhrase: "Revenue increased by 15% in Q4.",
 *   anchorText: "increased by 15%",
 *   citationNumber: 1,
 * };
 * ```
 */
export interface DocumentCitation extends CitationBase {
  /** Citation type discriminator. Required. */
  type: "document";

  /** Attachment ID for document citations */
  attachmentId?: string;

  /** Page number in the document */
  pageNumber?: number;

  /** Line IDs within the page */
  lineIds?: number[];

  /** Start page ID for multi-page citations */
  startPageId?: string;
}

/**
 * URL citation — web page or online resource.
 * Uses url, domain, title, etc. for verification.
 *
 * @example
 * ```typescript
 * const urlCitation: UrlCitation = {
 *   type: "url",
 *   url: "https://example.com/article",
 *   domain: "example.com",
 *   title: "Q4 Financial Report",
 *   fullPhrase: "The TGU transitions require control, not brute strength.",
 *   anchorText: "require control, not brute strength",
 *   citationNumber: 1,
 * };
 * ```
 */
export interface UrlCitation extends CitationBase {
  /** Citation type discriminator. Required. */
  type: "url";

  /** The source URL */
  url?: string;

  /** Display domain (e.g., "example.com", "fitandwell.com") */
  domain?: string;

  /** Page/article title */
  title?: string;

  /** Brief description or snippet from the page */
  description?: string;

  /** Favicon URL for the source */
  faviconUrl?: string;

  /** Platform/source type for categorization (e.g., "video", "news", "social") */
  sourceType?: SourceType;

  /** Platform name (e.g., "Twitch", "YouTube", "Reddit") */
  platform?: string;

  /** Site name (e.g., "Fit&Well", "Garage Gym Reviews") */
  siteName?: string;

  /** Author name if available */
  author?: string;

  /** Publication date (ISO 8601 string) */
  publishedAt?: string;

  /** Open Graph or social media image URL */
  imageUrl?: string;

  /** When the source was accessed/verified (ISO 8601 string) */
  accessedAt?: string;
}

/**
 * Discriminated union for citations.
 *
 * Narrow with `citation.type === "url"` to get `UrlCitation`,
 * or `citation.type === "document"` to get `DocumentCitation`.
 *
 * Common fields (`fullPhrase`, `anchorText`, etc.) are accessible without narrowing.
 * Document-specific fields (`pageNumber`, `lineIds`, etc.) require narrowing first.
 */
export type Citation = DocumentCitation | UrlCitation;

/**
 * Type guard to check if a citation is a URL citation.
 * Narrows the Citation union to UrlCitation when true.
 */
export function isUrlCitation(citation: Citation): citation is UrlCitation {
  return citation.type === "url";
}

/**
 * Type guard to check if a citation is a document citation.
 * Narrows the Citation union to DocumentCitation when true.
 */
export function isDocumentCitation(citation: Citation): citation is DocumentCitation {
  return citation.type === "document";
}

export interface CitationStatus {
  isVerified: boolean;
  isMiss: boolean;
  isPartialMatch: boolean;
  isPending: boolean;
}

/**
 * Metadata for a source in an aggregated sources list.
 * Used by SourcesListComponent to display collected citations.
 */
interface SourceMeta {
  /** Unique identifier for this source */
  id: string;
  /** The source URL */
  url: string;
  /** Page/document title */
  title: string;
  /** Display domain without www prefix */
  domain: string;
  /** Platform/source type */
  sourceType?: SourceType;
  /** Favicon URL */
  faviconUrl?: string;
  /** Citation numbers that reference this source */
  citationNumbers?: number[];
  /** Number of times this source is cited */
  citationCount?: number;
  /** Relevant excerpts/quotes from this source */
  excerpts?: string[];
  /** Verification status if verified */
  verificationStatus?: "verified" | "partial" | "pending" | "failed" | "unknown";
  /** When the source was accessed (ISO 8601 string) */
  accessedAt?: string;
}
